### ISSUE TITLE
Project configuration sanity

### ISSUE THREAD

**Issue by pablocubico** [coralproject/elkhorn#1]
Some ideas to tidy up this repo:
- [ ] Clean unused dependencies in package.json
- [x] Rollup needs a slightly different `.babelrc` to include the `es2015-rollup` plugin, maybe we can point to a different `.babelrc` for rollup on build time.
- [ ] Create an NPM task that builds the ask bundle?

**Comment by impronunciable** [comment]
Had to do a weird trick to make the babel configuration on the server but it's working.

**Comment by jde** [comment]
@impronunciable Is this weird trick still in effect?  If so, what is it and how can we make it standard?  All of our apps should be able to be deployed in a straight forward manner.

**Comment by impronunciable** [comment]
@jde it was weird because I needed to require the babel config but it's not ugly code. It works really well, nothing to worry about and not interfering with the deployment.

This is the code I was talking about, nothing strange in the code https://github.com/coralproject/elkhorn/blob/master/server/builder.js#L8
